// To Avoid Plagarisim, I am openly disclaiming that I did not write this code
// This code was generated by ChatGPT from OpenAI


// fs is built into nodejs already, no need to install with npm
const fs = require('fs');  

function embed(path_to_file, message) {
  const file_content = fs.readFileSync(path_to_file, { encoding: 'utf8' });
  const modified_content = `/*MESSAGE:${message}*/\n${file_content}`;
  fs.writeFileSync(path_to_file, modified_content);
}


function decode(path_to_file) {
  const file_content = fs.readFileSync(path_to_file, { encoding: 'utf8' });
  const match = file_content.match(/\/\*MESSAGE:(.*?)\*\//);
  if (match) {
    console.log(match[1]);
  } else {
    console.log('No hidden message found!');
  }
}


function erase(path_to_file) {
  const file_content = fs.readFileSync(path_to_file, { encoding: 'utf8' });
  const modified_content = file_content.replace(/\/\*MESSAGE:.*?\*\//g, '');
  fs.writeFileSync(path_to_file, modified_content);
}
